### ISSUE TITLE
dhcperfcli -v command not found

### ISSUE THREAD

**Issue by Arthi1904** [nchaigne/dhcperfcli#2]
Hi,
We are trying to test dhcp performance.
We have followed the below link
https://github.com/nchaigne/dhcperfcli/blob/master/INSTALL.md
While trying "dhcperfcli -v" it says, command not found.

FYI: 
While running ./configure command, we added "--with-openssl=no"
Apart from that, all commands executed as expected. 

Kindly let us know, what are we missing. 
Looking forward for your response.

Thanks

**Comment by nchaigne** [comment]
Ah yes, there's an error in the "PATH" example update. The binary is installed in "bin", not "sbin".
So it should be, for example:

``export PATH=/opt/freeradius/4.0.x/bin:$PATH``
