### ISSUE TITLE
Upstream fix for a recent bug breaking DHCP broadcasts

### ISSUE THREAD

**Issue by terryburton** [nchaigne/dhcperfcli#3]
Please could you realign when this lands:

https://github.com/FreeRADIUS/freeradius-server/pull/3473

**Comment by nchaigne** [comment]
Awesome!
I had noticed some tests breaking but couldn't find the time to look into it.
Thanks a lot :)

**Comment by nchaigne** [comment]
Done.

**Comment by terryburton** [comment]
Thanks.
